import SfaLayout from '@/Layouts/SfaLayout';
import { Head } from '@inertiajs/react';

type Metric = { label: string; value: string; change: string };
type Visit = { time: string; outlet: string; area: string; status: string; initials: string };

export default function SalesDashboard({ metrics, visits }: { metrics: Metric[]; visits: Visit[] }) {
    return (
        <SfaLayout area="sales">
            <Head title="Ringkasan Sales" />
            <div className="space-y-6">
                <section className="relative overflow-hidden rounded-2xl bg-[#123b31] px-6 py-7 text-white sm:px-8 sm:py-8"><div className="absolute -right-8 -top-20 h-64 w-64 rounded-full border-[36px] border-white/[0.04]" /><div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-xs font-medium text-emerald-200">Senin, 29 September 2026 <span className="px-1.5">•</span> Jakarta Selatan</p><h1 className="mt-3 text-[25px] font-bold tracking-tight sm:text-[30px]">Pagi, semangat hari ini! ☀</h1><p className="mt-2 max-w-lg text-sm leading-6 text-emerald-100/75">Kamu punya <b className="text-white">3 kunjungan</b> terjadwal. Selesaikan target harianmu dan jaga hubungan baik dengan outlet.</p></div><div className="flex shrink-0 items-center gap-3 rounded-xl border border-white/10 bg-white/[0.07] px-4 py-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-400/15 text-lg text-emerald-200">⌖</span><div><p className="text-[10px] text-emerald-100/65">Status kunjungan</p><p className="mt-1 text-xs font-semibold">Belum check-in</p></div><span className="h-2 w-2 rounded-full bg-amber-300" /></div></div></section>
                <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, index) => <article key={metric.label} className="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-medium text-slate-500">{metric.label}</p><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700">{['↗', '◎', '⌖', '▤'][index]}</span></div><p className="mt-4 text-[25px] font-bold tracking-tight text-slate-900">{metric.value}</p><p className="mt-2 text-[10px] font-medium text-slate-400">{metric.change}</p></article>)}</section>
                <section className="grid grid-cols-1 gap-5 xl:grid-cols-[1.35fr_1fr]">
                    <article className="rounded-xl border border-slate-200/80 bg-white p-5 sm:p-6"><div><h2 className="text-sm font-bold text-slate-900">Rute kunjungan hari ini</h2><p className="mt-1 text-xs text-slate-500">Jadwal kunjungan outlet kamu</p></div><div className="mt-5">{visits.map((visit, index) => <div key={visit.outlet} className="relative flex gap-4 pb-5 last:pb-0">{index < visits.length - 1 && <span className="absolute bottom-0 left-[17px] top-9 w-px bg-slate-200" />}<span className={visit.status === 'Selesai' ? 'relative z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-[10px] font-bold text-emerald-800' : 'relative z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-slate-200 bg-white text-[10px] font-bold text-slate-500'}>{visit.initials}</span><div className="flex min-w-0 flex-1 items-start justify-between gap-3 border-b border-slate-100 pb-4 last:border-0 last:pb-0"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-xs font-bold text-slate-800">{visit.outlet}</p><span className={visit.status === 'Selesai' ? 'rounded bg-emerald-50 px-1.5 py-0.5 text-[9px] font-semibold text-emerald-700' : 'rounded bg-slate-100 px-1.5 py-0.5 text-[9px] font-semibold text-slate-500'}>{visit.status}</span></div><p className="mt-1.5 truncate text-[10px] text-slate-400">{visit.area}</p></div><span className="shrink-0 text-[10px] font-semibold text-slate-500">{visit.time}</span></div></div>)}</div></article>
                    <article className="rounded-xl border border-slate-200/80 bg-white p-5 sm:p-6"><h2 className="text-sm font-bold text-slate-900">Target penjualan</h2><p className="mt-1 text-xs text-slate-500">Progres target bulan September</p><div className="mt-7 flex items-center justify-between gap-4"><div><p className="text-[28px] font-bold tracking-tight text-slate-900">Rp 18,4 jt</p><p className="mt-1 text-xs text-slate-400">dari target Rp 25 jt</p></div><span className="flex h-14 w-14 items-center justify-center rounded-full border-[5px] border-emerald-600 border-r-slate-100 text-xs font-bold text-emerald-800">74%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[74%] rounded-full bg-emerald-600" /></div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>Rp 0</span><span>Rp 25 jt</span></div><div className="mt-6 rounded-lg bg-emerald-50/80 p-3.5"><p className="text-xs font-semibold text-emerald-900">Kamu di jalur yang tepat!</p><p className="mt-1 text-[10px] leading-5 text-emerald-800/70">Penjualanmu naik 14,2% dibanding bulan lalu. Pertahankan momentum ini.</p></div></article>
                </section>
                <section className="flex items-center gap-3 rounded-xl border border-slate-200/80 bg-white px-5 py-4 sm:px-6"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-50 text-blue-700">✦</span><div><p className="text-xs font-bold text-slate-800">Tips hari ini</p><p className="mt-1 text-[11px] text-slate-500">Pastikan stok outlet tercatat sebelum membuat pesanan baru.</p></div></section>
            </div>
        </SfaLayout>
    );
}