import SfaLayout from '@/Layouts/SfaLayout';
import { Head } from '@inertiajs/react';

type Metric = { label: string; value: string; change: string };
type Salesperson = { name: string; region: string; sales: string; progress: number; initials: string };
const days = ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'];

export default function AdminDashboard({ metrics, weeklySales, topSales }: { metrics: Metric[]; weeklySales: number[]; topSales: Salesperson[] }) {
    return (
        <SfaLayout area="admin">
            <Head title="Ringkasan Admin" />
            <div className="space-y-6">
                <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
                    <div><p className="text-xs font-semibold text-emerald-700">Senin, 29 September 2026</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-slate-900 sm:text-[28px]">Ringkasan bisnis</h1><p className="mt-1.5 text-sm text-slate-500">Pantau performa penjualan dan aktivitas tim Anda.</p></div>
                    <span className="w-fit rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold text-slate-700 shadow-sm">▦ &nbsp; 1–29 September 2026 &nbsp;⌄</span>
                </section>
                <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, index) => <article key={metric.label} className="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-medium text-slate-500">{metric.label}</p><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700">{['↗', '▤', '⌖', '♙'][index]}</span></div><p className="mt-4 text-[25px] font-bold tracking-tight text-slate-900">{metric.value}</p><p className="mt-2 text-[10px] font-semibold text-emerald-700">{metric.change} <span className="font-normal text-slate-400">vs bulan lalu</span></p></article>)}</section>
                <section className="grid grid-cols-1 gap-5 xl:grid-cols-[1.55fr_1fr]">
                    <article className="rounded-xl border border-slate-200/80 bg-white p-5 sm:p-6"><div><h2 className="text-sm font-bold text-slate-900">Tren penjualan</h2><p className="mt-1 text-xs text-slate-500">Performa penjualan minggu ini</p></div><div className="mt-7 flex h-52 gap-4"><div className="flex flex-col justify-between pb-6 text-[10px] text-slate-400"><span>100 jt</span><span>75 jt</span><span>50 jt</span><span>25 jt</span><span>0</span></div><div className="relative flex flex-1 items-end justify-around gap-3 border-b border-l border-slate-100 px-2">{weeklySales.map((height, index) => <div key={days[index]} className="relative z-10 flex h-full flex-1 flex-col items-center justify-end"><div className={index === 5 ? 'w-full max-w-8 rounded-t-md bg-emerald-700' : 'w-full max-w-8 rounded-t-md bg-emerald-100'} style={{ height: String(height) + '%' }} /><span className="absolute -bottom-6 text-[10px] text-slate-400">{days[index]}</span></div>)}</div></div><p className="mt-9 text-[10px] text-slate-500"><span className="mr-1 inline-block h-2 w-2 rounded-sm bg-emerald-700" /> Penjualan aktual <span className="ml-4 mr-1 inline-block h-2 w-2 rounded-sm bg-emerald-100" /> Minggu sebelumnya</p></article>
                    <article className="rounded-xl border border-slate-200/80 bg-white p-5 sm:p-6"><h2 className="text-sm font-bold text-slate-900">Pencapaian target</h2><p className="mt-1 text-xs text-slate-500">Target penjualan bulanan</p><div className="mt-7 flex items-center gap-5"><div className="flex h-32 w-32 shrink-0 items-center justify-center rounded-full" style={{ background: 'conic-gradient(#047857 0% 74%, #e7efeb 74% 100%)' }}><div className="flex h-[104px] w-[104px] flex-col items-center justify-center rounded-full bg-white"><span className="text-[26px] font-bold">74%</span><span className="text-[10px] text-slate-400">tercapai</span></div></div><div className="space-y-4 text-xs"><div><p className="text-slate-400">Penjualan</p><p className="mt-1 font-bold">Rp 248,6 jt</p></div><div><p className="text-slate-400">Target</p><p className="mt-1 font-bold">Rp 335 jt</p></div></div></div><p className="mt-7 border-t border-slate-100 pt-4 text-xs text-slate-500">Perlu <b className="text-slate-800">Rp 86,4 jt</b> lagi untuk mencapai target.</p></article>
                </section>
                <section className="rounded-xl border border-slate-200/80 bg-white"><div className="border-b border-slate-100 px-5 py-4 sm:px-6"><h2 className="text-sm font-bold text-slate-900">Performa tim sales</h2><p className="mt-1 text-xs text-slate-500">Sales dengan pencapaian tertinggi bulan ini</p></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="text-[10px] font-semibold uppercase tracking-wider text-slate-400"><th className="px-6 py-3">Nama sales</th><th className="px-4 py-3">Wilayah</th><th className="px-4 py-3">Penjualan</th><th className="px-6 py-3">Target bulanan</th></tr></thead><tbody>{topSales.map((person) => <tr key={person.name} className="border-t border-slate-100 text-xs"><td className="px-6 py-3.5"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-100 text-[10px] font-bold text-emerald-800">{person.initials}</span><b>{person.name}</b></div></td><td className="px-4 py-3.5 text-slate-500">{person.region}</td><td className="px-4 py-3.5 font-semibold">{person.sales}</td><td className="px-6 py-3.5"><div className="flex items-center gap-2"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: String(person.progress) + '%' }} /></div><span>{person.progress}%</span></div></td></tr>)}</tbody></table></div></section>
            </div>
        </SfaLayout>
    );
}